version: '3.3'    
services:  
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: ./
      dockerfile: ./the-real-devops-challenge/Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurant
    ports:
      - 8080:8080
    depends_on:
      - mongo
volumes:
  mongo-data:
